version: '3.8'
services:
  myapp:
    image: my-test-image
    container_name: springboot-container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: my-shop
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234 && sleep 5" ]
      interval: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: my-redis-server
    ports:
      - "6379:6379"
    restart: always

