services:
  mysql:
    image: mysql:8.0.30
    container_name: my-db-server
    environment:
      MYSQL_ROOT_PASSWORD : 1234
      MYSQL_DATABASE: myshop
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306