version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myshop
    ports:
      - "3308:3306"
    volumes:
      - mysql_data_retry:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
    env_file:
      - .env

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/

  redis:
    image: redis:latest
    container_name: my-redis-server
    hostname: redis
    ports:
      - "6379:6379"
    restart: always


volumes:
  mysql_data_retry:


